import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here
// https://docusaurus.io/docs/sidebar

const sidebars: SidebarsConfig = {
  docSidebar: [{type: 'autogenerated', dirName: 'documentation' }],
};

export default sidebars;
